on: workflow_dispatch
name: install chromium
jobs:
  install_chromium:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3

      - name: Install Chromium
        run: |
          sudo apt update
          sudo apt install -y chromium-browser
          mkdir -p chromium
          cp -r /usr/lib/chromium-browser/* chromium/

      - name: Move Chromium to repo root
        run: mv chromium/* ./

      - name: List files
        run: ls -la
