on: workflow_dispatch
name: install chromium
jobs:
  install_chromium:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3

      - name: Install Chromium
        run: |
          sudo apt update
          sudo apt install -y chromium-browser

      - name: Find Chromium path
        run: which chromium-browser

      - name: Copy Chromium files to repo
        run: |
          mkdir -p chromium
          cp $(which chromium-browser) chromium/

      - name: List files
        run: ls -la chromium
